version: 2.1
jobs:
  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            #!/bin/bash -o pipefail
            echo "This is an integration step"
            exit 1 || true
          when: always
workflows:
  version: 2
  integration_workflow:
    jobs:
      - integration
